CREATE TABLE products (
 id UUID PRIMARY KEY, name VARCHAR(120) NOT NULL, description VARCHAR(500),
 bin VARCHAR(8) NOT NULL UNIQUE CHECK (bin ~ '^[0-9]{8}$'),
 status VARCHAR(16) NOT NULL CHECK (status IN ('ACTIVE','CANCELED')),
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, version BIGINT NOT NULL DEFAULT 0
);
